apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-deployment
  labels:
    app: vprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
      - name: vprofile
        image: week8registry.azurecr.io/vprofileapp:v1
        ports:
        - containerPort: 8080

