name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  IMAGE_NAME: vprofileapp
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .

      - name: Log in to ACR
        run: |
          az acr login --name $REGISTRY_NAME

      - name: Push Docker image
        run: |
          docker push $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: $AKS_RESOURCE_GROUP
          cluster-name: $AKS_CLUSTER_NAME

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/

