name: Fail If Secrets Missing

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if DB_PASSWORD is not set
        run: |
          if [ -z "${{ secrets.DB_PASSWORD }}" ]; then
            echo "❌ DB_PASSWORD is not set!"
            exit 1
          fi

      - name: Fail if API_KEY is not set
        run: |
          if [ -z "${{ secrets.API_KEY }}" ]; then
            echo "❌ API_KEY is not set!"
            exit 1
          fi

      - name: Echo Secrets
        run: |
          echo "✅ DB_PASSWORD and API_KEY are set"

