name: Main Pipeline With Staged Variables

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/task-group.yml
    with:
      STAGE_NAME: "Build"
      STAGE_VAR: "build-value"
    secrets:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Set in GitHub > Settings > Secrets

  deploy:
    uses: ./.github/workflows/task-group.yml
    with:
      STAGE_NAME: "Deploy"
      STAGE_VAR: "deploy-value"
    secrets:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

