name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:
  call-task-group:
    uses: ./.github/workflows/task-group.yml
    with:
      STAGE_NAME: "Deploy"
      STAGE_VAR: "deploy-stage"
    secrets:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}

