name: Main Pipeline with Task Groups

on:
  push:
    branches:
      - main

jobs:
  Build:
    uses: ./.github/workflows/task-group.yml
    with:
      STAGE_NAME: "Build"
      STAGE_VAR: "build-value"

  Deploy:
    uses: ./.github/workflows/task-group.yml
    with:
      STAGE_NAME: "Deploy"
      STAGE_VAR: "deploy-value"

