name: Reusable Task Group

on:
  workflow_call:
    inputs:
      STAGE_NAME:
        required: true
        type: string
      STAGE_VAR:
        required: true
        type: string
    secrets:
      DB_PASSWORD:
        required: true
      API_KEY:
        required: true

jobs:
  run-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Stage Name: ${{ inputs.STAGE_NAME }}"
          echo "Stage Variable: ${{ inputs.STAGE_VAR }}"

      - name: Print Secrets
        run: |
          echo "DB_PASSWORD is: ${{ secrets.DB_PASSWORD }}"
          echo "API_KEY is: ${{ secrets.API_KEY }}"

